name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 给脚本执行权限
      - name: Make script executable
        run: chmod +x package.sh

      # 使用自定义脚本打包
      - name: Custom package with MossLib
        run: ./package.sh

      # 上传JAR文件
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoBoxFrpClient
          path: target/MoBoxFrpClient.jar
          compression-level: 0  # 不压缩